name: Desplegar a entorno producción
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar script de despliegue
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRD_SSH_HOST }}
          username: ${{ secrets.PRD_SSH_USER }}
          key: ${{ secrets.PRD_SSH_KEY }}
          script: |
            php -v
            cd htdocs/feriapuntoverde.com
            git reset --hard HEAD
            git pull origin main
            composer install
            npm install
            php artisan route:cache
            php artisan config:cache
            php artisan view:cache
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan event:clear
            php artisan optimize:clear
            php artisan optimize
            npm run build

